# This is a basic workflow to help you get started with Actions

name: Deploy to Lambda Function

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ main , release]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      LAMBDA_PACKAGED_FILE: jasperreports-1.0.1.jar

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout workspace
        uses: actions/checkout@v3

      - name: Set variables for development
        if: endsWith(github.ref, '/main')
        run: |
          echo "AWS_LAMBDA_FUNCTION_NAME=Dev_ReportGenerator" >> $GITHUB_ENV
          echo "AWS_LAMBDA_LAYER_NAME=Dev_ReportGeneratorLambdaLayer" >> $GITHUB_ENV
          echo "REPORTS_BUCKET=luis-data-extractor" >> $GITHUB_ENV
          echo "TEMPLATES_S3_BUCKET=luis-report-generator-lambda" >> $GITHUB_ENV
          echo "FILES_BUCKET=luis-data-extractor" >> $GITHUB_ENV
          echo "DYNAMODB_TABLE=luis_BillingStagingRecords" >> $GITHUB_ENV          

      - name: Set variables for production
        if: endsWith(github.ref, '/release')
        run: |
          echo "AWS_LAMBDA_FUNCTION_NAME=Prod_ReportGenerator" >> $GITHUB_ENV
          echo "AWS_LAMBDA_LAYER_NAME=Prod_ReportGeneratorLambdaLayer" >> $GITHUB_ENV
          echo "REPORTS_BUCKET=prod-billing-report-generator-files-bucket" >> $GITHUB_ENV          
          echo "TEMPLATES_S3_BUCKET=prod-billing-report-generator-templates-bucket" >> $GITHUB_ENV
          echo "FILES_BUCKET=prod-billing-data-extractor" >> $GITHUB_ENV
          echo "DYNAMODB_TABLE=Prod_BillingStagingRecords" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: build project
        run: mvn -B package --file lambda_code/pom.xml 

      - name: Configure Secrets
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-skip-session-tagging: true
          aws-access-key-id: 'AKIAY2JTJFWK23CRIBEK'
          aws-secret-access-key: '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'
          aws-region: us-west-2
          role-to-assume: lambda_function_deploy
          role-external-id:  lsandoval
          role-duration-seconds: 1200
          role-session-name: lambda_deployment
                
      - name: Deploy Code to AWS
        run: |
          zip -g reportGeneratorv4.zip lambda_code/target/classes
          aws s3 cp reportGeneratorv4.zip s3://$TEMPLATES_S3_BUCKET/lambda/
          aws lambda update-function-configuration --function-name $AWS_LAMBDA_FUNCTION_NAME --environment "Variables={DYNAMODB_TABLE=$DYNAMODB_TABLE, FILES_BUCKET=$FILES_BUCKET, LAMBDA_BUCKET=$TEMPLATES_S3_BUCKET, REPORTS_BUCKET=$REPORTS_BUCKET}"
          aws lambda update-function-code --function-name $AWS_LAMBDA_FUNCTION_NAME --s3-bucket $TEMPLATES_S3_BUCKET --s3-key lambda/reportGeneratorv4.zip
      - name: Create New Layer Version
        run: |
          aws lambda publish-layer-version --layer-name $AWS_LAMBDA_LAYER_NAME --zip-file fileb://lambda_code/target/$LAMBDA_PACKAGED_FILE --compatible-runtimes python3.7 --region $AWS_REGION
      - name: Update Lambda Function Layer Version to Lastest or Add Layer
        run: |
          layer=$(aws lambda list-layer-versions --layer-name $AWS_LAMBDA_LAYER_NAME --query 'max_by(LayerVersions, &Version).LayerVersionArn' | grep -P $AWS_LAMBDA_LAYER_NAME | sed -e 's/\"//g' -e 's/\,//g')
          aws lambda update-function-configuration --function-name $AWS_LAMBDA_FUNCTION_NAME --layers $layer
      - name: Trim Lambda Layer versions
        uses: callummackenzie/trim-lambda-layers-action@v0.3
        with:
          aws_access_key_id: ${{ secrets.AWS_SECRET_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_region: us-west-2
          layer_name: ${{ env.AWS_LAMBDA_LAYER_NAME }}
          version_keep_count: 1    
           
