# This is a basic workflow to help you get started with Actions

name: Upload Templates Folder

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" and "release" branches
  push:
    branches: [ main , release]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TEMPLATES_LOGO1: "iUGOCareW@3x.png"
      TEMPLATES_LOGO2: "iUGOCareLogo2.png"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout workspace
        uses: actions/checkout@v3

      - name: Set variables for development
        if: endsWith(github.ref, '/main')
        run: |
          echo "TEMPLATES_S3_BUCKET=dev-billing-report-generator-templates-bucket" >> $GITHUB_ENV
          echo "ENVIRONMENTS_FILE=development_environments.json" >> $GITHUB_ENV
          

      - name: Set variables for production
        if: endsWith(github.ref, '/release')
        run: |
          echo "TEMPLATES_S3_BUCKET=prod-billing-report-generator-templates-bucket" >> $GITHUB_ENV
          echo "ENVIRONMENTS_FILE=production_environments.json" >> $GITHUB_ENV
      
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: build project
        run: mvn -B package --file templates/pom.xml 
          
      - name: Configure Secrets
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-skip-session-tagging: true
          aws-access-key-id: ${{ secrets.AWS_SECRET_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-external-id:  ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          role-duration-seconds: 1200
          role-session-name: lambda_deployment

      - name: Deploy Templates to AWS
        run: |
          aws s3 cp templates/pdf s3://$TEMPLATES_S3_BUCKET/pdf-templates --recursive
          aws s3 cp templates/excel s3://$TEMPLATES_S3_BUCKET/excel-templates --recursive
          aws s3 cp templates/target/compiled/pdf s3://$TEMPLATES_S3_BUCKET/pdf-templates --recursive
          aws s3 cp templates/target/compiled/excel s3://$TEMPLATES_S3_BUCKET/excel-templates --recursive
      - name: Upload Environments file to s3
        run: |
          aws s3 cp environments/$ENVIRONMENTS_FILE s3://$TEMPLATES_S3_BUCKET/environments/apiEndpoints.json
      - name: Upload templates logo image
        run: |
          aws s3 cp templates/assets/$TEMPLATES_LOGO1 s3://$TEMPLATES_S3_BUCKET/images/$TEMPLATES_LOGO1
          aws s3 cp templates/assets/$TEMPLATES_LOGO2 s3://$TEMPLATES_S3_BUCKET/images/$TEMPLATES_LOGO2
